import Head from "next/head";
import CategoryShowcase from "../components/CategoryShowcase";
import Header from "../components/Header";
import Hero from "../components/Hero";
import catHoodie from "../public/static/cathoodie.jpg";
import catMen from "../public/static/catmen.jpg";
import catWomen from "../public/static/catwomen.jpg";
import catAccesories from "../public/static/cataccesories.jpg";
import productPic from "../public/static/vans.jpg";
import SingleProduct from "../components/SingleProduct";
import About from "../components/About";
import Footer from "../components/Footer";
import LatestProducts from "../components/LatestProducts";

export default function Home() {
  return (
    <div className="ml-4 mr-4 ">
      <Head>
        <title>Sneaker Industry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/logo.png" />
      </Head>

      <Hero />
      <div className="flex items-center justify-between flex-wrap gap-6">
        <CategoryShowcase categoryName="Sneakers men" categorySrc={catMen} />
        <CategoryShowcase
          categoryName="Sneakers women"
          categorySrc={catWomen}
        />
        <CategoryShowcase categoryName="clothing" categorySrc={catAccesories} />
        <CategoryShowcase categoryName="Accesories" categorySrc={catHoodie} />
      </div>
      <LatestProducts />
      <section className="mt-4 mb-40">
        <h1 className="text-center uppercase -ml-4 -mr-4 text-2xl text-white bg-black p-10 mb-4">
          best sellers
        </h1>
        <div className="flex gap-8 flex-wrap justify-center ">
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
          <SingleProduct
            width="w-full"
            height="h-60"
            src={productPic}
            brand="vans"
            model="Authentic 44 DX"
            sizes={["36", "36.5", "37", "38", "39", "40", "41"]}
            price="389,00"
          />
        </div>
      </section>
      <About />
    </div>
  );
}
